### ISSUE TITLE
Css not applying to code

### ISSUE THREAD

**Issue by anthonyaubrey** [anthonyaubrey/dsn1675-assignment-1#1]
I cant seem to figure out why my css is not changing the appearance of my code. My css folder shows up on git hub aswell.  @thomasjbradley 
![untitled](https://cloud.githubusercontent.com/assets/10467688/9881265/309b5b44-5b9d-11e5-8c86-698d64506b6a.png)

**Comment by thomasjbradley** [comment]
It looks like there's a validation error on this line here:
https://github.com/anthonyaubrey/dsn1675-assignment-1/blob/gh-pages/index.html#L4

**Comment by anthonyaubrey** [comment]
Oh wow, thank you kindly Thomas! @thomasjbradley
